---

- name: Sync soure from git
  git:
    repo='https://github.com/google/benchmark.git'
    accept_hostkey=yes
    clone=yes
    dest='{{goobly_cache_dir}}/google_benchmark'
    update=yes
    recursive=yes
    version='v0.1.0'

- name: configure with cmake
  command: cmake .
  args:
    chdir: '{{goobly_cache_dir}}/google_benchmark'
    creates: '{{goobly_cache_dir}}/google_benchmark/Makefile'

- name: build
  command: make -j{{ansible_processor_vcpus}}
  args:
    chdir: '{{goobly_cache_dir}}/google_benchmark'
    creates: '{{goobly_cache_dir}}/google_benchmark/src/libbenchmark.a'
