---

- name: Sync soure from git
  git:
    repo='https://github.com/pmem/nvml.git'
    accept_hostkey=yes
    clone=yes
    dest='{{goobly_cache_dir}}/nvml'
    update=yes
    recursive=yes
    version='0.4'
    force=yes

- name: Compile
  command: make -j{{ansible_processor_vcpus}}
  args:
    chdir: '{{goobly_cache_dir}}/nvml'
    creates: '{{goobly_cache_dir}}/nvml/src/nondebug/libpmemlog.so'
